name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Kernel Build
      run: source build.sh beyond2lte
    - name: Show information about build
      run: cat build.info
    - name: Upload Kernel
      uses: actions/upload-artifact@v1
      with:
        name: CruelKernelLos
        path: boot.img
    - name: Upload Kernel Info
      uses: actions/upload-artifact@v1
      with:
        name: ConfigurationInfo
        path: build.info
