name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Kernel Build
      run: source build.sh beyond2lte
    - name: Upload Kernel
      uses: actions/upload-artifact@v1
      with:
        name: Los-Zunaid
        path: build/beyond2lte-eur.img
    - name: Upload Kernel Info
      uses: actions/upload-artifact@v1
